// config/theme.ts
export const theme = {
  light: {
    colors: {
      primary: '#fd9e3a',
      secondary: '#ff7f50',
      accent: '#ffaa60',
      background: '#ffffff',
      surface: '#f4f4f4',
      cardBg: '#f8f8f8',
      text: '#222222',
      mutedText: '#555555',
      border: '#eaeaea',
      link: '#fd9e3a',
      linkHover: '#e65a1c',
      success: '#28a745',
      warning: '#ffc107',
      error: '#dc3545',
      info: '#17a2b8',
    },
    typography: {
      fontFamily: "'Segoe UI', Roboto, sans-serif",
      fontSize: '16px',
      fontSizeSm: '14px',
      fontSizeLg: '18px',
      lineHeight: 1.5,
    },
    layout: {
      spacing: '8px',
      borderRadius: '4px',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
      transition: '0.2s ease-in-out',
    },
  },
  dark: {
    colors: {
      primary: '#fd9e3a',
      secondary: '#ff8c42',
      accent: '#ffb374',
      background: '#18181b',
      surface: '#1f1f23',
      cardBg: '#23272f',
      text: '#f3f4f6',
      mutedText: '#c2c2c2',
      border: '#333842',
      link: '#fd9e3a',
      linkHover: '#ffa12c',
      success: '#3dd598',
      warning: '#ffcf6b',
      error: '#ff6b6b',
      info: '#4ebcff',
    },
    typography: {
      fontFamily: "'Segoe UI', Roboto, sans-serif",
      fontSize: '16px',
      fontSizeSm: '14px',
      fontSizeLg: '18px',
      lineHeight: 1.5,
    },
    layout: {
      spacing: '8px',
      borderRadius: '4px',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.5)',
      transition: '0.2s ease-in-out',
    },
  },
};
